### ISSUE TITLE
html code in php code

### ISSUE THREAD

**Issue by Kidokyfe** [modxcms/Articles#59] opened 2013-12-15 15:29 UTC
Doesn't correspond to modx philosophy
![1](https://f.cloud.github.com/assets/6079787/1750576/ab05739e-659d-11e3-8024-2ee79ec1b322.JPG)

**Comment by jpdevries** [comment] 2013-12-15 17:10
Agreed

**Comment by JoshuaLuckers** [comment] 2019-05-31 21:51
This is a duplicate of #42

**Closed as completed by JoshuaLuckers** 2019-05-31 21:51 UTC
Labels: duplicate
