### ISSUE TITLE
No articles show in container or by snippet [[Articles]] with getpage-1.2.4-pl

### ISSUE THREAD

**Issue by Arialia** [modxcms/Articles#89] opened 2014-06-27 21:23 UTC
Well just upgrade my site from modx revo 2.1.1 to 2.2.4 ( last upgrade by Softcalous )
and so try Articles for my blog and well after upgrade all extra, just discover than i couldn't see myne articles , latest posts, tags, comments works fine but no articles in container .

Try snippet [[Articles]] in another ressources ... don't work.

[[Articles? &container=`281`]] don't work but

[[ !getResourcesTag?
  &;elementClass=`modSnippet`
  &element=`getResources`
  &tpl=`my.ArticleRowTpl`
  &tplFirst=`my.ArticleRowTpl`
  &parents=`281`
  &limit=`5`
  &includeContent=`1`
  &includeTVs=`1`
  &showHidden=`1`
  &hideContainers=`1`
  &cache=`0`
  &pageVarKey=`page`
]] works

i found the guilty : Articles use getPage for list of post and snippet getPage don't work directly now 
this code : 
[[!getPage? &element=`getResources` &parents=`281` &tpl=`my.ArticleRowTpl`]]
don't work with last getPage and last Articles.

So maybe using getRessource with pageVarkey= 'page'
in /core/components/articles/model/articles/articlescontainer.class.php will resolve that problem

In waiting i put a call to getRessouces before content of articles and it works

here extract my container template : 
<code>
 [[ !getResourcesTag?
  &elementClass=`modSnippet`
  &element=`getResources`
  &tpl=`my.ArticleRowTpl`
  &tplFirst=`my.ArticleRowTpl`
  &parents=`[[*id]]`
  &limit=`5`
  &includeContent=`1`
  &includeTVs=`1`
  &showHidden=`1`
  &hideContainers=`1`
  &cache=`0`
  &pageVarKey=`page`
]] 

[[*content]]

<aside>

 Latest Posts
  <ul>
  [[+latest_posts]]
  </ul>
[[+comments_enabled:is=`1`:then=`
  <h3>Latest Comments</h3>
  <ul>
  [[+latest_comments]]
  </ul>
`]]
    </aside>
</code>

PS : getRessourcesTag come with TagLister

**Comment by JoshuaLuckers** [comment] 2019-07-06 17:49
Thanks for taking time to report this issue and help make Articles better. Since this has been reported a long time ago and since I'm unable to reproduce this error I'm closing this issue.

**Closed as completed by JoshuaLuckers** 2019-07-06 17:49 UTC
