### ISSUE TITLE
Changes Pending Warning Constant and Innacurate

### ISSUE THREAD

**Issue by hephaestoskin** [modxcms/Articles#67] opened 2014-02-03 23:03 UTC
Whenever I navigate to an articles post resource, no matter if I have edited the resource or not, I always get the "You have changes pending" warning when hitting the close button.

**Comment by jpdevries** [comment] 2014-02-04 00:27
I've reproduced this in 2.2.21-dev (which fixes the issue with resources)—

**Comment by hephaestoskin** [comment] 2014-02-04 20:34
Despite updating to today's release of articles 1.7.6 this glitch is still present in modx 2.2.10

**Comment by jpdevries** [comment] 2014-02-04 20:39
The patch is for 2.2.12 which is still in dev—

**Comment by JoshuaLuckers** [comment] 2019-05-31 21:55
This issue is a duplicate of #55

**Closed as completed by JoshuaLuckers** 2019-05-31 21:55 UTC
Labels: duplicate
