### ISSUE TITLE
Any fix for pending chages bug?

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/Articles#75] opened 2014-03-26 21:42 UTC
"You have changes pending; are you sure you want to cancel?" always appears when closing an article
http://tracker.modx.com/issues/7558
Thanks

MODX Revolution 2.2.12-pl (traditional)

**Comment by jpdevries** [comment] 2014-03-26 22:39
At least we know people click this button :s

Will try and reproduce this, I thought it may have been fixed already
—

**Comment by shaunmorrison** [comment] 2014-03-27 15:31
Yes, I get the pending message twice – once from MODx and then another from my browser. Doubly annoying. Previously was 'only' a single message. 

MODx 2.2.12-pl and Articles 1.7.6

**Comment by clutchmarketingto** [comment] 2018-09-12 16:09
I am getting this same problem in MODX 2.6.5 and Articles 1.7.11

**Comment by JoshuaLuckers** [comment] 2019-05-31 22:00
This issue is a duplicate of #55

**Closed as completed by JoshuaLuckers** 2019-05-31 22:00 UTC
Labels: duplicate
