### ISSUE TITLE
Add ability to add tags to existing tags

### ISSUE THREAD

**Issue by rthrash** [modxcms/Articles#3] opened 2013-06-18 20:50 UTC
I would love to be able to add new tags to the existing tags without having to retype all the existing tags (a la WordPress).

Originally by bobray on 2013-05-26T04:38:29Z
Redmine ID: <a href="http://tracker.modx.com/issues/9945">9945</a>
Affects: Revolution-2.2.7-pl
Environment: All

**Comment by jpdevries** [comment] 2013-06-20 02:16
Duplicate of #2

**Closed as completed by jpdevries** 2013-06-20 02:16 UTC
