### ISSUE TITLE
If Articles is starting page, tags and dates does not work properly

### ISSUE THREAD

**Issue by KHysiek** [modxcms/Articles#38] opened 2013-10-25 06:10 UTC
This is because Articles expects tags and by-dates links at aaa.com/articles/tags/etc addresses but generates aaa.com/tags/etc.

This is a bug discussed and mentioned tenths times already but nobody cared to fix this. I've fixed this my way hacking articlesrouter, cause I could not find better (and simplest) solution, even submitted to github a year ago, still nobody cared. Whatever, I guess this is how modx works. If you find it usable here are my changes (older has updates, newer just comments):

https://github.com/KHysiek/Articles/commits/develop/core/components/articles/model/articles/articlesrouter.class.php

I would be very gratefuf if someone could finally apply this or any other fix to these tags and dates problems, so I don't have to manually edit this file every update.

**Comment by sepiariver** [comment] 2013-10-25 16:08
Hello KHysiek,

Thank you for your work on this, and submitting the issue. It's indeed a worthy bug to fix. FYI, Articles was developed and maintained by Shaun splittingred, who has since left the company. Unfortunately we didn't have anyone who could take over his extensive list of Extras, until very recently, so there is a back-log of issues.

We are trying very hard to update all of Shaun's Extras but I'm sure you can understand that we are a small team, and our software is free an open source, and there's just not that many people here that we can catch up so fast. Please be patient with us - we're trying our best.

And please do let us know about any more bugs you find - believe it or not, we value these contributions greatly :)

**Comment by jpdevries** [comment] 2013-10-26 22:13
@KHysiek I'd also like to apologize for this taking so long to be examined. I've got this merged into a testing branch here:
https://github.com/modxcms/Articles/commit/a43380b2c2e448a5f6208593a8c99fc7e9e6c104

Had to manually merge it because we have actually had multiple PRs related to the router class. In testing the branch, I actually found a somewhat related bug that is in the current released version of Articles:
https://github.com/modxcms/Articles/issues/39

It's safe to say that this router class needs some work, and I appreciate your contribution.

**Comment by jpdevries** [comment] 2013-10-26 22:44
I've confirmed that the issues I've recently discovered are not related to this PR, and are rather fundamental flaws with the current Articles router. I've merged this into the develop branch, so it's slated for the next release
https://github.com/modxcms/Articles/commit/a43380b2c2e448a5f6208593a8c99fc7e9e6c104

**Closed as completed by jpdevries** 2013-10-26 22:44 UTC
