### ISSUE TITLE
Cannot change 'Other listing parameters' again after saving Articles container

### ISSUE THREAD

**Issue by vierkantemeter** [modxcms/Articles#66] opened 2014-01-31 10:35 UTC
When I update an Articles container to add some listing parameters, the new value doesn't get saved. When I add the new value directly in the database it works.

For example I first had:
&tplFirst=`item.first.tpl`

And after saving and editing the container I changed it to:
&tvFilters=`mytv!=1` &includeTVs=`1` &includeTVList=`mytv`

I save the articles container, refresh the page and the value for Other listing parameters is once again:
&tplFirst=`item.first.tpl`

When I change it in the database and open the articles container in the manager the new value is there.

---

MODX Revolution 2.2.10
Articles 1.7.3

**Comment by JoshuaLuckers** [comment] 2019-07-06 17:42
Thanks for taking time to report this issue and help make Articles better. Since this has been reported a long time ago and since I'm unable to reproduce this error I'm closing this issue.

**Closed as completed by JoshuaLuckers** 2019-07-06 17:42 UTC
